spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: false
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  application:
      # 服务名称尽量用-，不要用_，不要用特殊字符
      name: content-center

server:
  port: 8011
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    com.wei.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
resttemplate:
  sentinel:
    # 设置成false，表示关闭@SentinelRestTemplate注解
    enabled: true
rocketmq:
  name-server: localhost:9876
  producer:
    # 小坑：必须指定group
    group: test-group
